name: build-tools

"on":
  push:
#    tags:
#      - v*
    paths:
      - .github/workflows/build-tools.yml

jobs:
  build-tools:
    runs-on: [ "self-hosted", "linux", "ARM64" ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}

      - name: Build && Push
        run:
          make dockerx.build-tools
