name: istio-envoy-build-env
"on":
  push:
    paths:
    - .github/workflows/build-build-env.yml
    - build/istio-envoy-build-env/Dockerfile.istio-envoy-build-env
    - build/istio-envoy-build-env/.version
    - build/istio-envoy-build-env/Makefile
jobs:
  istio-envoy-build-env:
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
    runs-on: ${{ matrix.arch != 'amd64' && fromJSON(format('["self-hosted","linux","{0}"]', matrix.arch)) || 'ubuntu-latest' }}
    defaults:
      run:
        working-directory: build/istio-envoy-build-env
    outputs:
      image: ${{ steps.prepare.outputs.image }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - uses: docker/login-action@v1
      name: Login ghcr.io
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - uses: docker/login-action@v1
      name: Login docker.io
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Build && May push
      env:
        DOCKERX_LABELS: org.opencontainers.image.source=https://github.com/${{ github.repository }} org.opencontainers.image.revision=${{ github.sha }}
        DOCKERX_NAME: istio-envoy-build-env
        DOCKERX_PLATFORMS: linux/${{ matrix.arch }}
        DOCKERX_PUSH: ${{ github.event_name != 'pull_request' }}
        DOCKERX_TAG_SUFFIX: -${{ matrix.arch }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        HUB: ghcr.io/querycap/istio docker.io/querycapistio
      run: |-
        if [[ ${GITHUB_REF} != "refs/heads/master" ]]; then
          export DOCKERX_TAGS=sha-${GITHUB_SHA::7}
        fi
        make dockerx
  istio-envoy-build-env-combine:
    if: ${{ github.event_name != 'pull_request' }}
    needs:
    - istio-envoy-build-env
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build/istio-envoy-build-env
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - uses: docker/login-action@v1
      name: Login ghcr.io
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - uses: docker/login-action@v1
      name: Login docker.io
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Combine
      env:
        DOCKERX_NAME: istio-envoy-build-env
        DOCKERX_PLATFORMS: linux/amd64 linux/arm64
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        HUB: ghcr.io/querycap/istio docker.io/querycapistio
      run: |-
        if [[ ${GITHUB_REF} != "refs/heads/master" ]]; then
          export DOCKERX_TAGS=sha-${GITHUB_SHA::7}
        fi
        make imagetools
