name: istio

"on":
  push:
    tags:
      - v*
    paths:
      - .github/workflows/istio.yml

jobs:
  envoy-arm64:
    runs-on: [ "self-hosted", "linux", "ARM64" ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}

      - run:
          make build.envoy

      #      # for debug
      #      - uses: dawidd6/action-download-artifact@v2
      #        with:
      #          workflow: envoy
      #          run_id: 1025483310
      #          name: envoy-linux-arm64
      #          path: .tmp/proxy/bazel-bin/src/envoy

      - uses: actions/upload-artifact@v2
        with:
          name: envoy-linux-arm64
          path: |
            .tmp/proxy/bazel-bin/src/envoy/envoy

  istio:
    needs:
      - envoy-arm64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}

      - uses: actions/download-artifact@v2
        with:
          name: envoy-linux-arm64
          path: .tmp/envoy-linux-arm64

      - run: make dockerx.istio